In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv(r"E:\engg\Data\E_Com\e_commerce_messy.csv")

In [5]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [6]:
df.describe()

               ID         Total
count  103.000000     89.000000
mean   149.640777   1232.949101
std     28.704326   2605.471455
min    100.000000 -20000.000000
25%    125.500000    582.130000
50%    149.000000   1138.760000
75%    174.500000   2153.400000
max    199.000000   4722.700000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

In [15]:
df.columns

AttributeError: 'NoneType' object has no attribute 'columns'

In [16]:
df.isnull().sum()

AttributeError: 'NoneType' object has no attribute 'isnull'

In [13]:
df=df.rename(columns={" Customer_Name": "Customer_Name", " Category":"Category"},inplace=True)

In [ ]:
df['Order_ID'].duplicated().sum()

np.int64(3)

In [25]:
df = df.drop_duplicates(subset=['Order_ID'], keep='first')

In [26]:
df["Order_ID"].duplicated().sum()

np.int64(0)

In [27]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [28]:
df.rename(columns={
  " Customer_Name" : "Customer_Name",
   " Category" : "Category" 
}, inplace=True)

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\3466066033.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={

In [29]:
df.columns

Index(['ID', 'Customer_Name', 'Order_ID', 'Order_Date', 'Product', 'Category',
       'Quantity', 'Price', 'Payment_Method', 'Status', 'Total'],
      dtype='object')

In [30]:
df['Category'] = df['Category'].fillna('Unknown')

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\2334677803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Category'].fillna('Unknown')

In [31]:
df['Price'] = pd.to_numeric(df['Price'].astype(str).str.replace('$', '', regex=False), errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\240521700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = pd.to_numeric(df['Price'].astype(str).str.replace('$', '', regex=False), errors='coerce')
C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\240521700.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [32]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Unknown,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [33]:
df['Category'] = df['Category'].str.strip().str.title()

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\2970371484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Category'].str.strip().str.title()

In [34]:
df['Quantity'] = df['Quantity'].abs()

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\2038587808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = df['Quantity'].abs()

In [35]:
df["Total"] = df["Quantity"] * df ["Price"]

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\4031938364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Total"] = df["Quantity"] * df ["Price"]

In [36]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,07-05-2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,6/19/2025,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,12/23/2024,Vacuum,Home,NaN,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Unknown,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [37]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce')

C:\Users\hunnu\AppData\Local\Temp\ipykernel_85492\2139354638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', errors='coerce')

In [38]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,2024-11-22,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,2024-12-23,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,2025-03-19,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,2025-10-20,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51
...,...,...,...,...,...,...,...,...,...,...,...
95,195,Customer_195,ORD-82876,2025-06-19,Biography,Books,5.0,817.46,Cash on Delivery,Returned,4087.30
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,Home,NaN,NaN,PayPal,Delivered,NaN
97,197,Customer_197,ORD-79139,2025-06-23,Blender,Home,1.0,160.16,PayPal,Cancelled,160.16
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,Unknown,2.0,497.01,Cash on Delivery,Shipped,994.02
99,199,Customer_199,ORD-82922,2025-01-22,Blender,Home,5.0,372.28,Credit Card,Shipped,1861.40

In [44]:
df[df['Order_Date'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
92,192,Customer_192,ORD-35144,NaT,Jacket,Clothing,NaN,203.63,Credit Card,Returned,NaN

In [40]:
df.duplicated().sum()

np.int64(0)